"""create students table

Revision ID: 40f76c346396
Revises: 
Create Date: 2026-05-27 15:50:08.159650

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '40f76c346396'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('students',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='Auto-incrementing surrogate primary key'),
    sa.Column('student_id', sa.String(length=50), nullable=False, comment='Unique student roll number or ID (e.g. STU-2024-001)'),
    sa.Column('full_name', sa.String(length=150), nullable=False, comment="Student's full legal name"),
    sa.Column('department', sa.String(length=100), nullable=False, comment='Department or faculty the student belongs to'),
    sa.Column('semester', sa.Integer(), nullable=False, comment='Current semester (e.g., 1 through 8)'),
    sa.Column('cgpa', sa.Float(), nullable=True, comment='Cumulative Grade Point Average'),
    sa.Column('attendance_percentage', sa.Float(), nullable=True, comment='Attendance percentage (0.0 to 100.0)'),
    sa.Column('library_visits', sa.Integer(), nullable=True, comment='Total number of library visits recorded'),
    sa.Column('assignments_completed', sa.Integer(), nullable=True, comment='Total number of assignments the student has completed'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when this record was created'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_students_id'), 'students', ['id'], unique=False)
    op.create_index(op.f('ix_students_student_id'), 'students', ['student_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_students_student_id'), table_name='students')
    op.drop_index(op.f('ix_students_id'), table_name='students')
    op.drop_table('students')
    # ### end Alembic commands ###
